# Generated by Django 4.0.4 on 2023-07-17 12:00

from django.db import migrations, models
import social_app.models


class Migration(migrations.Migration):

    dependencies = [
        ('social_app', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='image',
            field=models.ImageField(null=True, upload_to=social_app.models.post_img_file_path),
        ),
    ]
