# Generated by Django 4.0.4 on 2023-07-17 21:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('social_app', '0003_post_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='hashtag',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
