# Generated by Django 4.2.1 on 2023-07-19 10:49

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("social_app", "0005_alter_post_liked_by_delete_like"),
    ]

    operations = [
        migrations.AlterField(
            model_name="post",
            name="created_at",
            field=models.DateTimeField(),
        ),
    ]
