# Generated by Django 4.0.4 on 2023-07-17 07:56

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("user", "0004_blacklistedtoken"),
    ]

    operations = [
        migrations.DeleteModel(
            name="BlackListedToken",
        ),
    ]
